version: '3.8'
services:
  mrss-rabbitmq-broker:
    image: rabbitmq:3-management-alpine
    container_name: 'mrss-rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
  mrss-feed-handler-postgres:
    container_name: mrss-postgres-container
    restart: always
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'postgres', '-U', 'postgres']
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # Comment below to show mongo logs
    logging:
      driver: none
    image: postgres:14.1-alpine
    ports:
      - '5444:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./sql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
  mrss-feed-handler:
    container_name: mrss-service-container
    restart: on-failure:3
    build:
      context: .
      target: build
    ports:
      - '5000:5000'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/
    command: npm run start:dev
    depends_on:
      - mrss-feed-handler-postgres
      - mrss-rabbitmq-broker
    env_file:
      - .env.local
    environment:
      - FEED_HANDLER_POSTGRES_URI=postgres://postgres:postgres@mrss-postgres:5432
      - FEED_HANDLER_POSTGRES_DATABASE=feed-handler
      - FEED_HANDLER_FEED_REQUESTS_API_URL=http://localhost:5000
      - FEED_HANDLER_FEED_MONGODB_URI=abc
      - FEED_HANDLER_DISCORD_CLIENT_ID=123
      - FEED_HANDLER_DISCORD_RABBITMQ_URI=123
      - FEED_HANDLER_API_PORT=3001
      # Queue name is referenced in the elasticmq.conf file
      - FEED_HANDLER_FEED_EVENT_QUEUE_URL=http://mrss-feed-handler-feed-queue:9324/queue/feed-handler-feed-queue
      - FEED_HANDLER_AWS_REGION=us-east-1
      - FEED_HANDLER_AWS_SECRET_ACCESS_KEY=123
      - FEED_HANDLER_AWS_ACCESS_KEY_ID=123
      - FEED_HANDLER_RABBITMQ_BROKER_URL=amqp://guest:guest@mrss-rabbitmq-broker:5672

volumes:
  db:
    driver: local
