version: '3.8'
services:
  mrss-postgres:
    container_name: mrss-postgres-container
    restart: always
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'postgres', '-U', 'postgres']
      timeout: 45s
      interval: 10s
      retries: 10
    # command: mongod --port 27017
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # Comment below to show mongo logs
    # logging:
    #   driver: none
    image: postgres:14.1-alpine
    ports:
      - '5444:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./sql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
  mrss-service:
    container_name: mrss-service-container
    restart: on-failure:3
    # The image can also be used
    # image: synzen/monitorss
    build:
      context: .
      target: build
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/
    command: npm run start:dev
    depends_on:
      - mrss-postgres
    env_file:
      - .env.local
    environment:
      - POSTGRES_URI=postgres://postgres:postgres@mrss-postgres:5432/feedfetcher

volumes:
  db:
    driver: local
