version: '3.8'
services:
  request-queue:
    image: s12v/elasticmq
    volumes:
      - ./elasticmq.conf:/etc/elasticmq/elasticmq.conf
    ports:
      - '9324:9324'
      - '9325:9325'
  mrss-mongo:
    restart: on-failure:5
    command: mongod --port 27017
    logging:
      driver: none
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - "db-mongodb-data:/data/db"
  mrss-postgres:
    container_name: mrss-postgres-container
    restart: always
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'postgres', '-U', 'postgres']
      timeout: 45s
      interval: 10s
      retries: 10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    # Comment below to show mongo logs
    # logging:
    #   driver: none
    image: postgres:14.1-alpine
    ports:
      - '5444:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./sql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
  mrss-service:
    container_name: mrss-service-container
    restart: on-failure:3
    # The image can also be used
    build:
      context: .
      target: build
    ports:
      - '5000:5000'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/
    command: npm run start
    depends_on:
      - mrss-postgres
      - request-queue
    env_file:
      - .env.local
    environment:
      - POSTGRES_URI=postgres://postgres:postgres@mrss-postgres:5432/feedfetcher
      - AWS_SQS_REQUEST_QUEUE_URL=http://localhost:9324/queue/request-queue
      - AWS_SQS_REQUEST_QUEUE_REGION=us-east-1
      - AWS_SQS_REQUEST_QUEUE_ENDPOINT=http://localhost:9324
      - FAILED_REQUEST_DURATION_THRESHOLD_HOURS=36
      - FEEDS_MONGODB_URI=mongodb://mrss-mongo:27017/feedfetcher
      - PORT=5000
      - SKIP_POLLING_SQS_REQUEST_QUEUE=false

volumes:
  db-mongodb-data:
  db:
    driver: local
